<?php

use App\SystemVariable;

function getTimeZones()
{
    return array(
        "Pacific/Midway" => "(UTC-11:00) Midway Island",
        "Pacific/Samoa" => "(UTC-11:00) Samoa",
        "Pacific/Honolulu" => "(UTC-10:00) Hawaii",
        "US/Alaska" => "(UTC-09:00) Alaska",
        "America/Los_Angeles" => "(UTC-08:00) Pacific Time (US &amp; Canada)",
        "America/Tijuana" => "(UTC-08:00) Tijuana",
        "US/Arizona" => "(UTC-07:00) Arizona",
        "America/Chihuahua" => "(UTC-07:00) Chihuahua",
        "America/Chihuahua" => "(UTC-07:00) La Paz",
        "America/Mazatlan" => "(UTC-07:00) Mazatlan",
        "US/Mountain" => "(UTC-07:00) Mountain Time (US &amp; Canada)",
        "America/Managua" => "(UTC-06:00) Central America",
        "US/Central" => "(UTC-06:00) Central Time (US &amp; Canada)",
        "America/Mexico_City" => "(UTC-06:00) Guadalajara",
        "America/Mexico_City" => "(UTC-06:00) Mexico City",
        "America/Monterrey" => "(UTC-06:00) Monterrey",
        "Canada/Saskatchewan" => "(UTC-06:00) Saskatchewan",
        "America/Bogota" => "(UTC-05:00) Bogota",
        "US/Eastern" => "(UTC-05:00) Eastern Time (US &amp; Canada)",
        "US/East-Indiana" => "(UTC-05:00) Indiana (East)",
        "America/Lima" => "(UTC-05:00) Lima",
        "America/Bogota" => "(UTC-05:00) Quito",
        "Canada/Atlantic" => "(UTC-04:00) Atlantic Time (Canada)",
        "America/Caracas" => "(UTC-04:30) Caracas",
        "America/La_Paz" => "(UTC-04:00) La Paz",
        "America/Santiago" => "(UTC-04:00) Santiago",
        "Canada/Newfoundland" => "(UTC-03:30) Newfoundland",
        "America/Sao_Paulo" => "(UTC-03:00) Brasilia",
        "America/Argentina/Buenos_Aires" => "(UTC-03:00) Buenos Aires",
        "America/Argentina/Buenos_Aires" => "(UTC-03:00) Georgetown",
        "America/Godthab" => "(UTC-03:00) Greenland",
        "America/Noronha" => "(UTC-02:00) Mid-Atlantic",
        "Atlantic/Azores" => "(UTC-01:00) Azores",
        "Atlantic/Cape_Verde" => "(UTC-01:00) Cape Verde Is.",
        "Africa/Casablanca" => "(UTC+00:00) Casablanca",
        "Europe/London" => "(UTC+00:00) Edinburgh",
        "Etc/Greenwich" => "(UTC+00:00) Greenwich Mean Time : Dublin",
        "Europe/Lisbon" => "(UTC+00:00) Lisbon",
        "Europe/London" => "(UTC+00:00) London",
        "Africa/Monrovia" => "(UTC+00:00) Monrovia",
        "UTC" => "(UTC+00:00) UTC",
        "Europe/Amsterdam" => "(UTC+01:00) Amsterdam",
        "Europe/Belgrade" => "(UTC+01:00) Belgrade",
        "Europe/Berlin" => "(UTC+01:00) Berlin",
        "Europe/Berlin" => "(UTC+01:00) Bern",
        "Europe/Bratislava" => "(UTC+01:00) Bratislava",
        "Europe/Brussels" => "(UTC+01:00) Brussels",
        "Europe/Budapest" => "(UTC+01:00) Budapest",
        "Europe/Copenhagen" => "(UTC+01:00) Copenhagen",
        "Europe/Ljubljana" => "(UTC+01:00) Ljubljana",
        "Europe/Madrid" => "(UTC+01:00) Madrid",
        "Europe/Paris" => "(UTC+01:00) Paris",
        "Europe/Prague" => "(UTC+01:00) Prague",
        "Europe/Rome" => "(UTC+01:00) Rome",
        "Europe/Sarajevo" => "(UTC+01:00) Sarajevo",
        "Europe/Skopje" => "(UTC+01:00) Skopje",
        "Europe/Stockholm" => "(UTC+01:00) Stockholm",
        "Europe/Vienna" => "(UTC+01:00) Vienna",
        "Europe/Warsaw" => "(UTC+01:00) Warsaw",
        "Africa/Lagos" => "(UTC+01:00) West Central Africa",
        "Europe/Zagreb" => "(UTC+01:00) Zagreb",
        "Europe/Athens" => "(UTC+02:00) Athens",
        "Europe/Bucharest" => "(UTC+02:00) Bucharest",
        "Africa/Cairo" => "(UTC+02:00) Cairo",
        "Africa/Harare" => "(UTC+02:00) Harare",
        "Europe/Helsinki" => "(UTC+02:00) Helsinki",
        "Europe/Istanbul" => "(UTC+02:00) Istanbul",
        "Asia/Jerusalem" => "(UTC+02:00) Jerusalem",
        "Europe/Helsinki" => "(UTC+02:00) Kyiv",
        "Africa/Johannesburg" => "(UTC+02:00) Pretoria",
        "Europe/Riga" => "(UTC+02:00) Riga",
        "Europe/Sofia" => "(UTC+02:00) Sofia",
        "Europe/Tallinn" => "(UTC+02:00) Tallinn",
        "Europe/Vilnius" => "(UTC+02:00) Vilnius",
        "Asia/Baghdad" => "(UTC+03:00) Baghdad",
        "Asia/Kuwait" => "(UTC+03:00) Kuwait",
        "Europe/Minsk" => "(UTC+03:00) Minsk",
        "Africa/Nairobi" => "(UTC+03:00) Nairobi",
        "Asia/Riyadh" => "(UTC+03:00) Riyadh",
        "Europe/Volgograd" => "(UTC+03:00) Volgograd",
        "Asia/Tehran" => "(UTC+03:30) Tehran",
        "Asia/Muscat" => "(UTC+04:00) Abu Dhabi",
        "Asia/Baku" => "(UTC+04:00) Baku",
        "Europe/Moscow" => "(UTC+04:00) Moscow",
        "Asia/Muscat" => "(UTC+04:00) Muscat",
        "Europe/Moscow" => "(UTC+04:00) St. Petersburg",
        "Asia/Tbilisi" => "(UTC+04:00) Tbilisi",
        "Asia/Yerevan" => "(UTC+04:00) Yerevan",
        "Asia/Kabul" => "(UTC+04:30) Kabul",
        "Asia/Karachi" => "(UTC+05:00) Islamabad",
        "Asia/Karachi" => "(UTC+05:00) Karachi",
        "Asia/Tashkent" => "(UTC+05:00) Tashkent",
        "Asia/Calcutta" => "(UTC+05:30) Chennai",
        "Asia/Kolkata" => "(UTC+05:30) Kolkata",
        "Asia/Calcutta" => "(UTC+05:30) Mumbai",
        "Asia/Calcutta" => "(UTC+05:30) New Delhi",
        "Asia/Calcutta" => "(UTC+05:30) Sri Jayawardenepura",
        "Asia/Katmandu" => "(UTC+05:45) Kathmandu",
        "Asia/Almaty" => "(UTC+06:00) Almaty",
        "Asia/Dhaka" => "(UTC+06:00) Astana",
        "Asia/Dhaka" => "(UTC+06:00) Dhaka",
        "Asia/Yekaterinburg" => "(UTC+06:00) Ekaterinburg",
        "Asia/Rangoon" => "(UTC+06:30) Rangoon",
        "Asia/Bangkok" => "(UTC+07:00) Bangkok",
        "Asia/Bangkok" => "(UTC+07:00) Hanoi",
        "Asia/Jakarta" => "(UTC+07:00) Jakarta",
        "Asia/Novosibirsk" => "(UTC+07:00) Novosibirsk",
        "Asia/Hong_Kong" => "(UTC+08:00) Beijing",
        "Asia/Chongqing" => "(UTC+08:00) Chongqing",
        "Asia/Hong_Kong" => "(UTC+08:00) Hong Kong",
        "Asia/Krasnoyarsk" => "(UTC+08:00) Krasnoyarsk",
        "Asia/Kuala_Lumpur" => "(UTC+08:00) Kuala Lumpur",
        "Australia/Perth" => "(UTC+08:00) Perth",
        "Asia/Singapore" => "(UTC+08:00) Singapore",
        "Asia/Taipei" => "(UTC+08:00) Taipei",
        "Asia/Ulan_Bator" => "(UTC+08:00) Ulaan Bataar",
        "Asia/Urumqi" => "(UTC+08:00) Urumqi",
        "Asia/Irkutsk" => "(UTC+09:00) Irkutsk",
        "Asia/Tokyo" => "(UTC+09:00) Osaka",
        "Asia/Tokyo" => "(UTC+09:00) Sapporo",
        "Asia/Seoul" => "(UTC+09:00) Seoul",
        "Asia/Tokyo" => "(UTC+09:00) Tokyo",
        "Australia/Adelaide" => "(UTC+09:30) Adelaide",
        "Australia/Darwin" => "(UTC+09:30) Darwin",
        "Australia/Brisbane" => "(UTC+10:00) Brisbane",
        "Australia/Canberra" => "(UTC+10:00) Canberra",
        "Pacific/Guam" => "(UTC+10:00) Guam",
        "Australia/Hobart" => "(UTC+10:00) Hobart",
        "Australia/Melbourne" => "(UTC+10:00) Melbourne",
        "Pacific/Port_Moresby" => "(UTC+10:00) Port Moresby",
        "Australia/Sydney" => "(UTC+10:00) Sydney",
        "Asia/Yakutsk" => "(UTC+10:00) Yakutsk",
        "Asia/Vladivostok" => "(UTC+11:00) Vladivostok",
        "Pacific/Auckland" => "(UTC+12:00) Auckland",
        "Pacific/Fiji" => "(UTC+12:00) Fiji",
        "Pacific/Kwajalein" => "(UTC+12:00) International Date Line West",
        "Asia/Kamchatka" => "(UTC+12:00) Kamchatka",
        "Asia/Magadan" => "(UTC+12:00) Magadan",
        "Pacific/Fiji" => "(UTC+12:00) Marshall Is.",
        "Asia/Magadan" => "(UTC+12:00) New Caledonia",
        "Asia/Magadan" => "(UTC+12:00) Solomon Is.",
        "Pacific/Auckland" => "(UTC+12:00) Wellington",
        "Pacific/Tongatapu" => "(UTC+13:00) Nuku'alofa",
    );
}

function getCountryCodes()
{
    return array(
        "DKK" => array("value" => "", "title" => "Select country code"),
        "AF" => array("value" => "93", "title" => "Afghanistan (+93)"),
        "AL" => array("value" => "355", "title" => "Albania (+355)"),
        "DZ" => array("value" => "213", "title" => "Algeria (+213)"),
        "AD" => array("value" => "376", "title" => "Andorra (+376)"),
        "AO" => array("value" => "244", "title" => "Angola (+244)"),
        "AI" => array("value" => "1264", "title" => "Anguilla (+1264)"),
        "AG" => array("value" => "1268", "title" => "Antigua &amp; Barbuda (+1268)"),
        "AR" => array("value" => "54", "title" => "Argentina (+54)"),
        "AM" => array("value" => "374", "title" => "Armenia (+374)"),
        "AW" => array("value" => "297", "title" => "Aruba (+297)"),
        "AU" => array("value" => "61", "title" => "Australia (+61)"),
        "AT" => array("value" => "43", "title" => "Austria (+43)"),
        "AZ" => array("value" => "994", "title" => "Azerbaijan (+994)"),
        "BS" => array("value" => "1242", "title" => "Bahamas (+1242)"),
        "BH" => array("value" => "973", "title" => "Bahrain (+973)"),
        "BD" => array("value" => "880", "title" => "Bangladesh (+880)"),
        "BB" => array("value" => "1246", "title" => "Barbados (+1246)"),
        "BY" => array("value" => "375", "title" => "Belarus (+375)"),
        "BE" => array("value" => "32", "title" => "Belgium (+32)"),
        "BZ" => array("value" => "501", "title" => "Belize (+501)"),
        "BJ" => array("value" => "229", "title" => "Benin (+229)"),
        "BM" => array("value" => "1441", "title" => "Bermuda (+1441)"),
        "BT" => array("value" => "975", "title" => "Bhutan (+975)"),
        "BO" => array("value" => "591", "title" => "Bolivia (+591)"),
        "BA" => array("value" => "387", "title" => "Bosnia Herzegovina (+387)"),
        "BW" => array("value" => "267", "title" => "Botswana (+267)"),
        "BR" => array("value" => "55", "title" => "Brazil (+55)"),
        "BN" => array("value" => "673", "title" => "Brunei (+673)"),
        "BG" => array("value" => "359", "title" => "Bulgaria (+359)"),
        "BF" => array("value" => "226", "title" => "Burkina Faso (+226)"),
        "BI" => array("value" => "257", "title" => "Burundi (+257)"),
        "KH" => array("value" => "855", "title" => "Cambodia (+855)"),
        "CM" => array("value" => "237", "title" => "Cameroon (+237)"),
        "CA" => array("value" => "1", "title" => "Canada (+1)"),
        "CV" => array("value" => "238", "title" => "Cape Verde Islands (+238)"),
        "KY" => array("value" => "1345", "title" => "Cayman Islands (+1345)"),
        "CF" => array("value" => "236", "title" => "Central African Republic (+236)"),
        "CL" => array("value" => "56", "title" => "Chile (+56)"),
        "CN" => array("value" => "86", "title" => "China (+86)"),
        "CO" => array("value" => "57", "title" => "Colombia (+57)"),
        "KM" => array("value" => "269", "title" => "Comoros (+269)"),
        "CG" => array("value" => "242", "title" => "Congo (+242)"),
        "CK" => array("value" => "682", "title" => "Cook Islands (+682)"),
        "CR" => array("value" => "506", "title" => "Costa Rica (+506)"),
        "HR" => array("value" => "385", "title" => "Croatia (+385)"),
        "CU" => array("value" => "53", "title" => "Cuba (+53)"),
        "CY" => array("value" => "90392", "title" => "Cyprus North (+90392)"),
        "CY" => array("value" => "357", "title" => "Cyprus South (+357)"),
        "CZ" => array("value" => "42", "title" => "Czech Republic (+42)"),
        "DK" => array("value" => "45", "title" => "Denmark (+45)"),
        "DJ" => array("value" => "253", "title" => "Djibouti (+253)"),
        "DM" => array("value" => "1809", "title" => "Dominica (+1809)"),
        "DO" => array("value" => "1809", "title" => "Dominican Republic (+1809)"),
        "EC" => array("value" => "593", "title" => "Ecuador (+593)"),
        "EG" => array("value" => "20", "title" => "Egypt (+20)"),
        "SV" => array("value" => "503", "title" => "El Salvador (+503)"),
        "GQ" => array("value" => "240", "title" => "Equatorial Guinea (+240)"),
        "ER" => array("value" => "291", "title" => "Eritrea (+291)"),
        "EE" => array("value" => "372", "title" => "Estonia (+372)"),
        "ET" => array("value" => "251", "title" => "Ethiopia (+251)"),
        "FK" => array("value" => "500", "title" => "Falkland Islands (+500)"),
        "FO" => array("value" => "298", "title" => "Faroe Islands (+298)"),
        "FJ" => array("value" => "679", "title" => "Fiji (+679)"),
        "FI" => array("value" => "358", "title" => "Finland (+358)"),
        "FR" => array("value" => "33", "title" => "France (+33)"),
        "GF" => array("value" => "594", "title" => "French Guiana (+594)"),
        "PF" => array("value" => "689", "title" => "French Polynesia (+689)"),
        "GA" => array("value" => "241", "title" => "Gabon (+241)"),
        "GM" => array("value" => "220", "title" => "Gambia (+220)"),
        "GE" => array("value" => "7880", "title" => "Georgia (+7880)"),
        "DE" => array("value" => "49", "title" => "Germany (+49)"),
        "GH" => array("value" => "233", "title" => "Ghana (+233)"),
        "GI" => array("value" => "350", "title" => "Gibraltar (+350)"),
        "GR" => array("value" => "30", "title" => "Greece (+30)"),
        "GL" => array("value" => "299", "title" => "Greenland (+299)"),
        "GD" => array("value" => "1473", "title" => "Grenada (+1473)"),
        "GP" => array("value" => "590", "title" => "Guadeloupe (+590)"),
        "GU" => array("value" => "671", "title" => "Guam (+671)"),
        "GT" => array("value" => "502", "title" => "Guatemala (+502)"),
        "GN" => array("value" => "224", "title" => "Guinea (+224)"),
        "GW" => array("value" => "245", "title" => "Guinea - Bissau (+245)"),
        "GY" => array("value" => "592", "title" => "Guyana (+592)"),
        "HT" => array("value" => "509", "title" => "Haiti (+509)"),
        "HN" => array("value" => "504", "title" => "Honduras (+504)"),
        "HK" => array("value" => "852", "title" => "Hong Kong (+852)"),
        "HU" => array("value" => "36", "title" => "Hungary (+36)"),
        "IS" => array("value" => "354", "title" => "Iceland (+354)"),
        "IN" => array("value" => "91", "title" => "India (+91)"),
        "ID" => array("value" => "62", "title" => "Indonesia (+62)"),
        "IR" => array("value" => "98", "title" => "Iran (+98)"),
        "IQ" => array("value" => "964", "title" => "Iraq (+964)"),
        "IE" => array("value" => "353", "title" => "Ireland (+353)"),
        "IL" => array("value" => "972", "title" => "Israel (+972)"),
        "IT" => array("value" => "39", "title" => "Italy (+39)"),
        "JM" => array("value" => "1876", "title" => "Jamaica (+1876)"),
        "JP" => array("value" => "81", "title" => "Japan (+81)"),
        "JO" => array("value" => "962", "title" => "Jordan (+962)"),
        "KZ" => array("value" => "7", "title" => "Kazakhstan (+7)"),
        "KE" => array("value" => "254", "title" => "Kenya (+254)"),
        "KI" => array("value" => "686", "title" => "Kiribati (+686)"),
        "KP" => array("value" => "850", "title" => "Korea North (+850)"),
        "KR" => array("value" => "82", "title" => "Korea South (+82)"),
        "KW" => array("value" => "965", "title" => "Kuwait (+965)"),
        "KG" => array("value" => "996", "title" => "Kyrgyzstan (+996)"),
        "LA" => array("value" => "856", "title" => "Laos (+856)"),
        "LV" => array("value" => "371", "title" => "Latvia (+371)"),
        "LB" => array("value" => "961", "title" => "Lebanon (+961)"),
        "LS" => array("value" => "266", "title" => "Lesotho (+266)"),
        "LR" => array("value" => "231", "title" => "Liberia (+231)"),
        "LY" => array("value" => "218", "title" => "Libya (+218)"),
        "LI" => array("value" => "417", "title" => "Liechtenstein (+417)"),
        "LT" => array("value" => "370", "title" => "Lithuania (+370)"),
        "LU" => array("value" => "352", "title" => "Luxembourg (+352)"),
        "MO" => array("value" => "853", "title" => "Macao (+853)"),
        "MK" => array("value" => "389", "title" => "Macedonia (+389)"),
        "MG" => array("value" => "261", "title" => "Madagascar (+261)"),
        "MW" => array("value" => "265", "title" => "Malawi (+265)"),
        "MY" => array("value" => "60", "title" => "Malaysia (+60)"),
        "MV" => array("value" => "960", "title" => "Maldives (+960)"),
        "ML" => array("value" => "223", "title" => "Mali (+223)"),
        "MT" => array("value" => "356", "title" => "Malta (+356)"),
        "MH" => array("value" => "692", "title" => "Marshall Islands (+692)"),
        "MQ" => array("value" => "596", "title" => "Martinique (+596)"),
        "MR" => array("value" => "222", "title" => "Mauritania (+222)"),
        "YT" => array("value" => "269", "title" => "Mayotte (+269)"),
        "MX" => array("value" => "52", "title" => "Mexico (+52)"),
        "FM" => array("value" => "691", "title" => "Micronesia (+691)"),
        "MD" => array("value" => "373", "title" => "Moldova (+373)"),
        "MC" => array("value" => "377", "title" => "Monaco (+377)"),
        "MN" => array("value" => "976", "title" => "Mongolia (+976)"),
        "MS" => array("value" => "1664", "title" => "Montserrat (+1664)"),
        "MA" => array("value" => "212", "title" => "Morocco (+212)"),
        "MZ" => array("value" => "258", "title" => "Mozambique (+258)"),
        "MN" => array("value" => "95", "title" => "Myanmar (+95)"),
        "NA" => array("value" => "264", "title" => "Namibia (+264)"),
        "NR" => array("value" => "674", "title" => "Nauru (+674)"),
        "NP" => array("value" => "977", "title" => "Nepal (+977)"),
        "NL" => array("value" => "31", "title" => "Netherlands (+31)"),
        "NC" => array("value" => "687", "title" => "New Caledonia (+687)"),
        "NZ" => array("value" => "64", "title" => "New Zealand (+64)"),
        "NI" => array("value" => "505", "title" => "Nicaragua (+505)"),
        "NE" => array("value" => "227", "title" => "Niger (+227)"),
        "NG" => array("value" => "234", "title" => "Nigeria (+234)"),
        "NU" => array("value" => "683", "title" => "Niue (+683)"),
        "NF" => array("value" => "672", "title" => "Norfolk Islands (+672)"),
        "NP" => array("value" => "670", "title" => "Northern Marianas (+670)"),
        "NO" => array("value" => "47", "title" => "Norway (+47)"),
        "OM" => array("value" => "968", "title" => "Oman (+968)"),
        "PW" => array("value" => "680", "title" => "Palau (+680)"),
        "PS" => array("value" => "970", "title" => "Palestine (+970)"),
        "PA" => array("value" => "507", "title" => "Panama (+507)"),
        "PG" => array("value" => "675", "title" => "Papua New Guinea (+675)"),
        "PY" => array("value" => "595", "title" => "Paraguay (+595)"),
        "PE" => array("value" => "51", "title" => "Peru (+51)"),
        "PH" => array("value" => "63", "title" => "Philippines (+63)"),
        "PL" => array("value" => "48", "title" => "Poland (+48)"),
        "PT" => array("value" => "351", "title" => "Portugal (+351)"),
        "PR" => array("value" => "1787", "title" => "Puerto Rico (+1787)"),
        "QA" => array("value" => "974", "title" => "Qatar (+974)"),
        "RE" => array("value" => "262", "title" => "Reunion (+262)"),
        "RO" => array("value" => "40", "title" => "Romania (+40)"),
        "RU" => array("value" => "7", "title" => "Russia (+7)"),
        "RW" => array("value" => "250", "title" => "Rwanda (+250)"),
        "SM" => array("value" => "378", "title" => "San Marino (+378)"),
        "ST" => array("value" => "239", "title" => "Sao Tome &amp; Principe (+239)"),
        "SA" => array("value" => "966", "title" => "Saudi Arabia (+966)"),
        "SN" => array("value" => "221", "title" => "Senegal (+221)"),
        "CS" => array("value" => "381", "title" => "Serbia (+381)"),
        "SC" => array("value" => "248", "title" => "Seychelles (+248)"),
        "SL" => array("value" => "232", "title" => "Sierra Leone (+232)"),
        "SG" => array("value" => "65", "title" => "Singapore (+65)"),
        "SK" => array("value" => "421", "title" => "Slovak Republic (+421)"),
        "SI" => array("value" => "386", "title" => "Slovenia (+386)"),
        "SB" => array("value" => "677", "title" => "Solomon Islands (+677)"),
        "SO" => array("value" => "252", "title" => "Somalia (+252)"),
        "ZA" => array("value" => "27", "title" => "South Africa (+27)"),
        "ES" => array("value" => "34", "title" => "Spain (+34)"),
        "LK" => array("value" => "94", "title" => "Sri Lanka (+94)"),
        "SH" => array("value" => "290", "title" => "St. Helena (+290)"),
        "KN" => array("value" => "1869", "title" => "St. Kitts (+1869)"),
        "SC" => array("value" => "1758", "title" => "St. Lucia (+1758)"),
        "SD" => array("value" => "249", "title" => "Sudan (+249)"),
        "SR" => array("value" => "597", "title" => "Suriname (+597)"),
        "SZ" => array("value" => "268", "title" => "Swaziland (+268)"),
        "SE" => array("value" => "46", "title" => "Sweden (+46)"),
        "CH" => array("value" => "41", "title" => "Switzerland (+41)"),
        "SI" => array("value" => "963", "title" => "Syria (+963)"),
        "TW" => array("value" => "886", "title" => "Taiwan (+886)"),
        "TJ" => array("value" => "7", "title" => "Tajikstan (+7)"),
        "TH" => array("value" => "66", "title" => "Thailand (+66)"),
        "TG" => array("value" => "228", "title" => "Togo (+228)"),
        "TO" => array("value" => "676", "title" => "Tonga (+676)"),
        "TT" => array("value" => "1868", "title" => "Trinidad &amp; Tobago (+1868)"),
        "TN" => array("value" => "216", "title" => "Tunisia (+216)"),
        "TR" => array("value" => "90", "title" => "Turkey (+90)"),
        "TM" => array("value" => "7", "title" => "Turkmenistan (+7)"),
        "TM" => array("value" => "993", "title" => "Turkmenistan (+993)"),
        "TC" => array("value" => "1649", "title" => "Turks &amp; Caicos Islands (+1649)"),
        "TV" => array("value" => "688", "title" => "Tuvalu (+688)"),
        "UG" => array("value" => "256", "title" => "Uganda (+256)"),
        "UA" => array("value" => "380", "title" => "Ukraine (+380)"),
        "GB" => array("value" => "44", "title" => "UK (+44)"),
        "AE" => array("value" => "971", "title" => "United Arab Emirates (+971)"),
        "UY" => array("value" => "598", "title" => "Uruguay (+598)"),
        "US" => array("value" => "1", "title" => "USA (+1)"),
        "UZ" => array("value" => "7", "title" => "Uzbekistan (+7)"),
        "VU" => array("value" => "678", "title" => "Vanuatu (+678)"),
        "VA" => array("value" => "379", "title" => "Vatican City (+379)"),
        "VE" => array("value" => "58", "title" => "Venezuela (+58)"),
        "VN" => array("value" => "84", "title" => "Vietnam (+84)"),
        "VG" => array("value" => "84", "title" => "Virgin Islands - British (+1284)"),
        "VI" => array("value" => "84", "title" => "Virgin Islands - US (+1340)"),
        "WF" => array("value" => "681", "title" => "Wallis &amp; Futuna (+681)"),
        "YE" => array("value" => "969", "title" => "Yemen (North)(+969)"),
        "YE" => array("value" => "967", "title" => "Yemen (South)(+967)"),
        "ZM" => array("value" => "260", "title" => "Zambia (+260)"),
        "ZW" => array("value" => "263", "title" => "Zimbabwe (+263)"),

    );
}

function getCountries()
{
    return array(
        "" => "Select Country",
        "Afghanistan" => "Afghanistan",
        "Albania" => "Albania",
        "Algeria" => "Algeria",
        "American Samoa" => "American Samoa",
        "Andorra" => "Andorra",
        "Angola" => "Angola",
        "Anguilla" => "Anguilla",
        "Antartica" => "Antarctica",
        "Antigua and Barbuda" => "Antigua and Barbuda",
        "Argentina" => "Argentina",
        "Armenia" => "Armenia",
        "Aruba" => "Aruba",
        "Australia" => "Australia",
        "Austria" => "Austria",
        "Azerbaijan" => "Azerbaijan",
        "Bahamas" => "Bahamas",
        "Bahrain" => "Bahrain",
        "Bangladesh" => "Bangladesh",
        "Barbados" => "Barbados",
        "Belarus" => "Belarus",
        "Belgium" => "Belgium",
        "Belize" => "Belize",
        "Benin" => "Benin",
        "Bermuda" => "Bermuda",
        "Bhutan" => "Bhutan",
        "Bolivia" => "Bolivia",
        "Bosnia and Herzegowina" => "Bosnia and Herzegowina",
        "Botswana" => "Botswana",
        "Bouvet Island" => "Bouvet Island",
        "Brazil" => "Brazil",
        "British Indian Ocean Territory" => "British Indian Ocean Territory",
        "Brunei Darussalam" => "Brunei Darussalam",
        "Bulgaria" => "Bulgaria",
        "Burkina Faso" => "Burkina Faso",
        "Burundi" => "Burundi",
        "Cambodia" => "Cambodia",
        "Cameroon" => "Cameroon",
        "Canada" => "Canada",
        "Cape Verde" => "Cape Verde",
        "Cayman Islands" => "Cayman Islands",
        "Central African Republic" => "Central African Republic",
        "Chad" => "Chad",
        "Chile" => "Chile",
        "China" => "China",
        "Christmas Island" => "Christmas Island",
        "Cocos Islands" => "Cocos (Keeling) Islands",
        "Colombia" => "Colombia",
        "Comoros" => "Comoros",
        "Congo" => "Congo",
        "Congo" => "Congo, the Democratic Republic of the",
        "Cook Islands" => "Cook Islands",
        "Costa Rica" => "Costa Rica",
        "Cota D'Ivoire" => "Cote d'Ivoire",
        "Croatia" => "Croatia (Hrvatska)",
        "Cuba" => "Cuba",
        "Cyprus" => "Cyprus",
        "Czech Republic" => "Czech Republic",
        "Denmark" => "Denmark",
        "Djibouti" => "Djibouti",
        "Dominica" => "Dominica",
        "Dominican Republic" => "Dominican Republic",
        "East Timor" => "East Timor",
        "Ecuador" => "Ecuador",
        "Egypt" => "Egypt",
        "El Salvador" => "El Salvador",
        "Equatorial Guinea" => "Equatorial Guinea",
        "Eritrea" => "Eritrea",
        "Estonia" => "Estonia",
        "Ethiopia" => "Ethiopia",
        "Falkland Islands" => "Falkland Islands (Malvinas)",
        "Faroe Islands" => "Faroe Islands",
        "Fiji" => "Fiji",
        "Finland" => "Finland",
        "France" => "France",
        "France Metropolitan" => "France, Metropolitan",
        "French Guiana" => "French Guiana",
        "French Polynesia" => "French Polynesia",
        "French Southern Territories" => "French Southern Territories",
        "Gabon" => "Gabon",
        "Gambia" => "Gambia",
        "Georgia" => "Georgia",
        "Germany" => "Germany",
        "Ghana" => "Ghana",
        "Gibraltar" => "Gibraltar",
        "Greece" => "Greece",
        "Greenland" => "Greenland",
        "Grenada" => "Grenada",
        "Guadeloupe" => "Guadeloupe",
        "Guam" => "Guam",
        "Guatemala" => "Guatemala",
        "Guinea" => "Guinea",
        "Guinea-Bissau" => "Guinea-Bissau",
        "Guyana" => "Guyana",
        "Haiti" => "Haiti",
        "Heard and McDonald Islands" => "Heard and Mc Donald Islands",
        "Holy See" => "Holy See (Vatican City State)",
        "Honduras" => "Honduras",
        "Hong Kong" => "Hong Kong",
        "Hungary" => "Hungary",
        "Iceland" => "Iceland",
        "India" => "India",
        "Indonesia" => "Indonesia",
        "Iran" => "Iran (Islamic Republic of)",
        "Iraq" => "Iraq",
        "Ireland" => "Ireland",
        "Israel" => "Israel",
        "Italy" => "Italy",
        "Jamaica" => "Jamaica",
        "Japan" => "Japan",
        "Jordan" => "Jordan",
        "Kazakhstan" => "Kazakhstan",
        "Kenya" => "Kenya",
        "Kiribati" => "Kiribati",
        "Democratic People's Republic of Korea" => "Korea, Democratic People's Republic of",
        "Korea" => "Korea, Republic of",
        "Kuwait" => "Kuwait",
        "Kyrgyzstan" => "Kyrgyzstan",
        "Lao" => "Lao People's Democratic Republic",
        "Latvia" => "Latvia",
        "Lebanon" => "Lebanon",
        "Lesotho" => "Lesotho",
        "Liberia" => "Liberia",
        "Libyan Arab Jamahiriya" => "Libyan Arab Jamahiriya",
        "Liechtenstein" => "Liechtenstein",
        "Lithuania" => "Lithuania",
        "Luxembourg" => "Luxembourg",
        "Macau" => "Macau",
        "Macedonia" => "Macedonia, The Former Yugoslav Republic of",
        "Madagascar" => "Madagascar",
        "Malawi" => "Malawi",
        "Malaysia" => "Malaysia",
        "Maldives" => "Maldives",
        "Mali" => "Mali",
        "Malta" => "Malta",
        "Marshall Islands" => "Marshall Islands",
        "Martinique" => "Martinique",
        "Mauritania" => "Mauritania",
        "Mauritius" => "Mauritius",
        "Mayotte" => "Mayotte",
        "Mexico" => "Mexico",
        "Micronesia" => "Micronesia, Federated States of",
        "Moldova" => "Moldova, Republic of",
        "Monaco" => "Monaco",
        "Mongolia" => "Mongolia",
        "Montserrat" => "Montserrat",
        "Morocco" => "Morocco",
        "Mozambique" => "Mozambique",
        "Myanmar" => "Myanmar",
        "Namibia" => "Namibia",
        "Nauru" => "Nauru",
        "Nepal" => "Nepal",
        "Netherlands" => "Netherlands",
        "Netherlands Antilles" => "Netherlands Antilles",
        "New Caledonia" => "New Caledonia",
        "New Zealand" => "New Zealand",
        "Nicaragua" => "Nicaragua",
        "Niger" => "Niger",
        "Nigeria" => "Nigeria",
        "Niue" => "Niue",
        "Norfolk Island" => "Norfolk Island",
        "Northern Mariana Islands" => "Northern Mariana Islands",
        "Norway" => "Norway",
        "Oman" => "Oman",
        "Pakistan" => "Pakistan",
        "Palau" => "Palau",
        "Palestine" => "Palestine",
        "Panama" => "Panama",
        "Papua New Guinea" => "Papua New Guinea",
        "Paraguay" => "Paraguay",
        "Peru" => "Peru",
        "Philippines" => "Philippines",
        "Pitcairn" => "Pitcairn",
        "Poland" => "Poland",
        "Portugal" => "Portugal",
        "Puerto Rico" => "Puerto Rico",
        "Palestine" => "Palestine",
        "Qatar" => "Qatar",
        "Reunion" => "Reunion",
        "Romania" => "Romania",
        "Russia" => "Russian Federation",
        "Rwanda" => "Rwanda",
        "Saint Kitts and Nevis" => "Saint Kitts and Nevis",
        "Saint LUCIA" => "Saint LUCIA",
        "Saint Vincent" => "Saint Vincent and the Grenadines",
        "Samoa" => "Samoa",
        "San Marino" => "San Marino",
        "Sao Tome and Principe" => "Sao Tome and Principe",
        "Saudi Arabia" => "Saudi Arabia",
        "Senegal" => "Senegal",
        "Seychelles" => "Seychelles",
        "Sierra" => "Sierra Leone",
        "Singapore" => "Singapore",
        "Slovakia" => "Slovakia (Slovak Republic)",
        "Slovenia" => "Slovenia",
        "Solomon Islands" => "Solomon Islands",
        "Somalia" => "Somalia",
        "South Africa" => "South Africa",
        "South Georgia" => "South Georgia and the South Sandwich Islands",
        "Spain" => "Spain",
        "SriLanka" => "Sri Lanka",
        "St. Helena" => "St. Helena",
        "St. Pierre and Miguelon" => "St. Pierre and Miquelon",
        "Sudan" => "Sudan",
        "Suriname" => "Suriname",
        "Svalbard" => "Svalbard and Jan Mayen Islands",
        "Swaziland" => "Swaziland",
        "Sweden" => "Sweden",
        "Switzerland" => "Switzerland",
        "Syria" => "Syrian Arab Republic",
        "Taiwan" => "Taiwan, Province of China",
        "Tajikistan" => "Tajikistan",
        "Tanzania" => "Tanzania, United Republic of",
        "Thailand" => "Thailand",
        "Togo" => "Togo",
        "Tokelau" => "Tokelau",
        "Tonga" => "Tonga",
        "Trinidad and Tobago" => "Trinidad and Tobago",
        "Tunisia" => "Tunisia",
        "Turkey" => "Turkey",
        "Turkmenistan" => "Turkmenistan",
        "Turks and Caicos" => "Turks and Caicos Islands",
        "Tuvalu" => "Tuvalu",
        "Uganda" => "Uganda",
        "Ukraine" => "Ukraine",
        "United Arab Emirates" => "United Arab Emirates",
        "United Kingdom" => "United Kingdom",
        "United States" => "United States",
        "United States Minor Outlying Islands" => "United States Minor Outlying Islands",
        "Uruguay" => "Uruguay",
        "Uzbekistan" => "Uzbekistan",
        "Vanuatu" => "Vanuatu",
        "Vatican City" => "Vatican City",
        "Venezuela" => "Venezuela",
        "Vietnam" => "Viet Nam",
        "Virgin Islands (British)" => "Virgin Islands (British)",
        "Virgin Islands (U.S)" => "Virgin Islands (U.S.)",
        "Wallis and Futana Islands" => "Wallis and Futuna Islands",
        "Western Sahara" => "Western Sahara",
        "Yemen" => "Yemen",
        "Yugoslavia" => "Yugoslavia",
        "Zambia" => "Zambia",
        "Zimbabwe" => "Zimbabwe",
    );
}

function getNationalities()
{
    return array(
        "" => "Nationality",
        "Afghanistan" => "Afghanistan",
        "Albania" => "Albania",
        "Algeria" => "Algeria",
        "American Samoa" => "American Samoa",
        "Andorra" => "Andorra",
        "Angola" => "Angola",
        "Anguilla" => "Anguilla",
        "Antartica" => "Antarctica",
        "Antigua and Barbuda" => "Antigua and Barbuda",
        "Argentina" => "Argentina",
        "Armenia" => "Armenia",
        "Aruba" => "Aruba",
        "Australia" => "Australia",
        "Austria" => "Austria",
        "Azerbaijan" => "Azerbaijan",
        "Bahamas" => "Bahamas",
        "Bahrain" => "Bahrain",
        "Bangladesh" => "Bangladesh",
        "Barbados" => "Barbados",
        "Belarus" => "Belarus",
        "Belgium" => "Belgium",
        "Belize" => "Belize",
        "Benin" => "Benin",
        "Bermuda" => "Bermuda",
        "Bhutan" => "Bhutan",
        "Bolivia" => "Bolivia",
        "Bosnia and Herzegowina" => "Bosnia and Herzegowina",
        "Botswana" => "Botswana",
        "Bouvet Island" => "Bouvet Island",
        "Brazil" => "Brazil",
        "British Indian Ocean Territory" => "British Indian Ocean Territory",
        "Brunei Darussalam" => "Brunei Darussalam",
        "Bulgaria" => "Bulgaria",
        "Burkina Faso" => "Burkina Faso",
        "Burundi" => "Burundi",
        "Cambodia" => "Cambodia",
        "Cameroon" => "Cameroon",
        "Canada" => "Canada",
        "Cape Verde" => "Cape Verde",
        "Cayman Islands" => "Cayman Islands",
        "Central African Republic" => "Central African Republic",
        "Chad" => "Chad",
        "Chile" => "Chile",
        "China" => "China",
        "Christmas Island" => "Christmas Island",
        "Cocos Islands" => "Cocos (Keeling) Islands",
        "Colombia" => "Colombia",
        "Comoros" => "Comoros",
        "Congo" => "Congo",
        "Congo" => "Congo, the Democratic Republic of the",
        "Cook Islands" => "Cook Islands",
        "Costa Rica" => "Costa Rica",
        "Cota D'Ivoire" => "Cote d'Ivoire",
        "Croatia" => "Croatia (Hrvatska)",
        "Cuba" => "Cuba",
        "Cyprus" => "Cyprus",
        "Czech Republic" => "Czech Republic",
        "Denmark" => "Denmark",
        "Djibouti" => "Djibouti",
        "Dominica" => "Dominica",
        "Dominican Republic" => "Dominican Republic",
        "East Timor" => "East Timor",
        "Ecuador" => "Ecuador",
        "Egypt" => "Egypt",
        "El Salvador" => "El Salvador",
        "Equatorial Guinea" => "Equatorial Guinea",
        "Eritrea" => "Eritrea",
        "Estonia" => "Estonia",
        "Ethiopia" => "Ethiopia",
        "Falkland Islands" => "Falkland Islands (Malvinas)",
        "Faroe Islands" => "Faroe Islands",
        "Fiji" => "Fiji",
        "Finland" => "Finland",
        "France" => "France",
        "France Metropolitan" => "France, Metropolitan",
        "French Guiana" => "French Guiana",
        "French Polynesia" => "French Polynesia",
        "French Southern Territories" => "French Southern Territories",
        "Gabon" => "Gabon",
        "Gambia" => "Gambia",
        "Georgia" => "Georgia",
        "Germany" => "Germany",
        "Ghana" => "Ghana",
        "Gibraltar" => "Gibraltar",
        "Greece" => "Greece",
        "Greenland" => "Greenland",
        "Grenada" => "Grenada",
        "Guadeloupe" => "Guadeloupe",
        "Guam" => "Guam",
        "Guatemala" => "Guatemala",
        "Guinea" => "Guinea",
        "Guinea-Bissau" => "Guinea-Bissau",
        "Guyana" => "Guyana",
        "Haiti" => "Haiti",
        "Heard and McDonald Islands" => "Heard and Mc Donald Islands",
        "Holy See" => "Holy See (Vatican City State)",
        "Honduras" => "Honduras",
        "Hong Kong" => "Hong Kong",
        "Hungary" => "Hungary",
        "Iceland" => "Iceland",
        "India" => "India",
        "Indonesia" => "Indonesia",
        "Iran" => "Iran (Islamic Republic of)",
        "Iraq" => "Iraq",
        "Ireland" => "Ireland",
        "Israel" => "Israel",
        "Italy" => "Italy",
        "Jamaica" => "Jamaica",
        "Japan" => "Japan",
        "Jordan" => "Jordan",
        "Kazakhstan" => "Kazakhstan",
        "Kenya" => "Kenya",
        "Kiribati" => "Kiribati",
        "Democratic People's Republic of Korea" => "Korea, Democratic People's Republic of",
        "Korea" => "Korea, Republic of",
        "Kuwait" => "Kuwait",
        "Kyrgyzstan" => "Kyrgyzstan",
        "Lao" => "Lao People's Democratic Republic",
        "Latvia" => "Latvia",
        "Lebanon" => "Lebanon",
        "Lesotho" => "Lesotho",
        "Liberia" => "Liberia",
        "Libyan Arab Jamahiriya" => "Libyan Arab Jamahiriya",
        "Liechtenstein" => "Liechtenstein",
        "Lithuania" => "Lithuania",
        "Luxembourg" => "Luxembourg",
        "Macau" => "Macau",
        "Macedonia" => "Macedonia, The Former Yugoslav Republic of",
        "Madagascar" => "Madagascar",
        "Malawi" => "Malawi",
        "Malaysia" => "Malaysia",
        "Maldives" => "Maldives",
        "Mali" => "Mali",
        "Malta" => "Malta",
        "Marshall Islands" => "Marshall Islands",
        "Martinique" => "Martinique",
        "Mauritania" => "Mauritania",
        "Mauritius" => "Mauritius",
        "Mayotte" => "Mayotte",
        "Mexico" => "Mexico",
        "Micronesia" => "Micronesia, Federated States of",
        "Moldova" => "Moldova, Republic of",
        "Monaco" => "Monaco",
        "Mongolia" => "Mongolia",
        "Montserrat" => "Montserrat",
        "Morocco" => "Morocco",
        "Mozambique" => "Mozambique",
        "Myanmar" => "Myanmar",
        "Namibia" => "Namibia",
        "Nauru" => "Nauru",
        "Nepal" => "Nepal",
        "Netherlands" => "Netherlands",
        "Netherlands Antilles" => "Netherlands Antilles",
        "New Caledonia" => "New Caledonia",
        "New Zealand" => "New Zealand",
        "Nicaragua" => "Nicaragua",
        "Niger" => "Niger",
        "Nigeria" => "Nigeria",
        "Niue" => "Niue",
        "Norfolk Island" => "Norfolk Island",
        "Northern Mariana Islands" => "Northern Mariana Islands",
        "Norway" => "Norway",
        "Oman" => "Oman",
        "Pakistan" => "Pakistan",
        "Palau" => "Palau",
        "Palestine" => "Palestine",
        "Panama" => "Panama",
        "Papua New Guinea" => "Papua New Guinea",
        "Paraguay" => "Paraguay",
        "Peru" => "Peru",
        "Philippines" => "Philippines",
        "Pitcairn" => "Pitcairn",
        "Poland" => "Poland",
        "Portugal" => "Portugal",
        "Puerto Rico" => "Puerto Rico",
        "Qatar" => "Qatar",
        "Reunion" => "Reunion",
        "Romania" => "Romania",
        "Russia" => "Russian Federation",
        "Rwanda" => "Rwanda",
        "Saint Kitts and Nevis" => "Saint Kitts and Nevis",
        "Saint LUCIA" => "Saint LUCIA",
        "Saint Vincent" => "Saint Vincent and the Grenadines",
        "Samoa" => "Samoa",
        "San Marino" => "San Marino",
        "Sao Tome and Principe" => "Sao Tome and Principe",
        "Saudi Arabia" => "Saudi Arabia",
        "Senegal" => "Senegal",
        "Seychelles" => "Seychelles",
        "Sierra" => "Sierra Leone",
        "Singapore" => "Singapore",
        "Slovakia" => "Slovakia (Slovak Republic)",
        "Slovenia" => "Slovenia",
        "Solomon Islands" => "Solomon Islands",
        "Somalia" => "Somalia",
        "South Africa" => "South Africa",
        "South Georgia" => "South Georgia and the South Sandwich Islands",
        "Spain" => "Spain",
        "SriLanka" => "Sri Lanka",
        "St. Helena" => "St. Helena",
        "St. Pierre and Miguelon" => "St. Pierre and Miquelon",
        "Sudan" => "Sudan",
        "Suriname" => "Suriname",
        "Svalbard" => "Svalbard and Jan Mayen Islands",
        "Swaziland" => "Swaziland",
        "Sweden" => "Sweden",
        "Switzerland" => "Switzerland",
        "Syria" => "Syrian Arab Republic",
        "Taiwan" => "Taiwan, Province of China",
        "Tajikistan" => "Tajikistan",
        "Tanzania" => "Tanzania, United Republic of",
        "Thailand" => "Thailand",
        "Togo" => "Togo",
        "Tokelau" => "Tokelau",
        "Tonga" => "Tonga",
        "Trinidad and Tobago" => "Trinidad and Tobago",
        "Tunisia" => "Tunisia",
        "Turkey" => "Turkey",
        "Turkmenistan" => "Turkmenistan",
        "Turks and Caicos" => "Turks and Caicos Islands",
        "Tuvalu" => "Tuvalu",
        "Uganda" => "Uganda",
        "Ukraine" => "Ukraine",
        "United Arab Emirates" => "United Arab Emirates",
        "United Kingdom" => "United Kingdom",
        "United States" => "United States",
        "United States Minor Outlying Islands" => "United States Minor Outlying Islands",
        "Uruguay" => "Uruguay",
        "Uzbekistan" => "Uzbekistan",
        "Vanuatu" => "Vanuatu",
        "Vatican City" => "Vatican City",
        "Venezuela" => "Venezuela",
        "Vietnam" => "Viet Nam",
        "Virgin Islands (British)" => "Virgin Islands (British)",
        "Virgin Islands (U.S)" => "Virgin Islands (U.S.)",
        "Wallis and Futana Islands" => "Wallis and Futuna Islands",
        "Western Sahara" => "Western Sahara",
        "Yemen" => "Yemen",
        "Yugoslavia" => "Yugoslavia",
        "Zambia" => "Zambia",
        "Zimbabwe" => "Zimbabwe",
    );
}

function getMonth()
{
    return array(
        "" => "Month",
        "01" => "January",
        "02" => "February",
        "03" => "March",
        "04" => "April",
        "05" => "May",
        "06" => "June",
        "07" => "July",
        "08" => "August",
        "09" => "September",
        "10" => "October",
        "11" => "November",
        "12" => "December",
    );
}

function getVisitorInformation()
{
    $ipdata = @json_decode(file_get_contents("http://www.geoplugin.net/json.gp?ip=" . (!empty($_SERVER['HTTP_X_FORWARDED_FOR']) ? $_SERVER['HTTP_X_FORWARDED_FOR'] : $_SERVER['REMOTE_ADDR'])));
    $info = new StdClass();
    $info->timezone = "";
    $info->countryname = "";
    $info->countrycode = "";
    $info->nationality = "";
    if (@strlen(trim($ipdata->geoplugin_countryCode)) == 2) {
        $countryname = $ipdata->geoplugin_countryName;
        $countries = getCountries();
        foreach ($countries as $k => $v) {
            if (strtolower($k) == strtolower($countryname)) {
                $info->countryname = $k;
                break;
            }
        }

        $timezonedata = @json_decode(file_get_contents("https://maps.googleapis.com/maps/api/timezone/json?location=" . $ipdata->geoplugin_latitude . "," . $ipdata->geoplugin_longitude . "&timestamp=" . time() . "&sensor=false"));

        if (isset($timezonedata->timeZoneId) && !empty($timezonedata->timeZoneId)) {
            $timezone = $timezonedata->timeZoneId;
            $timezones = getTimeZones();
            foreach ($timezones as $k => $v) {
                if (strtolower($k) == strtolower($timezone)) {
                    $info->timezone = $k;
                    break;
                }
            }
        }

        $countries = getNationalities();
        foreach ($countries as $k => $v) {
            if (strtolower($k) == strtolower($countryname)) {
                $info->nationality = $k;
                break;
            }
        }

        $countries = getCountryCodes();
        foreach ($countries as $k => $v) {
            if (is_array($v) && isset($v[$ipdata->geoplugin_countryCode])) {
                $info->countrycode = $v[$ipdata->geoplugin_countryCode]['value'];
                break;
            } else if ($k == $ipdata->geoplugin_countryCode) {
                $info->countrycode = $v['value'];
                break;
            }
        }

    }

    return $info;
}

function getFavicon()
{
    $ico = SystemVariable::where('key', '=', 'website_favicon')->first();
    if ($ico && $ico->value)
        return 'uploads/site/' . $ico->value;

    return 'images/favicon.ico';
}

function getLogo()
{
    $logo = SystemVariable::where('key', '=', 'website_logo')->first();
    if ($logo && $logo->value)
        return 'uploads/site/' . $logo->value;

    return 'images/logo.png';
}

function getSiteName()
{
    static $siteName = null;
    if ($siteName != null)
        return $siteName;
    $name = SystemVariable::where('key', '=', 'website_name')->first();
    if ($name && $name->value)
        $siteName = $name->value;
    else
        $siteName = 'Payments Hub';

    return $siteName;
}

function isCallUsEnabled()
{
    $callUsEnabled = SystemVariable::where('key', '=', 'call_us_enabled')->first();
    return ($callUsEnabled && $callUsEnabled->value);
}

// add by m
function isSupportTicketEnabled()
{
    $SupportTicketEnabled = SystemVariable::where('key', '=', 'support_ticket_enabled')->first();
    return ($SupportTicketEnabled && $SupportTicketEnabled->value);
}

// add by m
function isSupportemail()
{
    $SupportTicketEnabled = SystemVariable::where('key', '=', 'support_email')->first();
    echo $SupportTicketEnabled->value;
}

// add by m
function isSupportphone()
{
    $SupportTicketEnabled = SystemVariable::where('key', '=', 'support_phone')->first();
    echo $SupportTicketEnabled->value;
}